version: "3"

services: 
  api:
    build: 
      context: ./api
    command: npm start
    user: "node"
    ports: 
      - "3000:3000"
    volumes:
      - ./api:/usr/api
    links:
      - db:banco

  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=coclima"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
